---

- name: Set storage mode
  notify: restart systemd-journald
  ini_file:
    dest: "{{ journald_config_file }}"
    section: Journal
    option: Storage
    value: "{{ journald_storage }}"
    no_extra_spaces: yes

- name: Set compression
  notify: restart systemd-journald
  ini_file:
    dest: "{{ journald_config_file }}"
    section: Journal
    option: Compress
    value: "{{ journald_compress }}"
    no_extra_spaces: yes

- name: Set max usage
  notify: restart systemd-journald
  ini_file:
    dest: "{{ journald_config_file }}"
    section: Journal
    option: SystemMaxUse
    value: "{{ journald_system_max_use }}"
    no_extra_spaces: yes
